java sprint 10 v1.0
1EVILGUN1/java-filmorate pull request #2
Opened 2024-07-09 10:38 UTC by 1EVILGUN1

добавлены зависимости в pom.xml
добавлены класс User, Film
классы-контроллеры UserController,FilmController, менеджер-класс Manager, обратка ошибок по валидации ValidationException

2024-07-09 19:36 UTC, 1EVILGUN1 commented
Viktory

2024-07-09 19:56 UTC, YazykovMikhail commented
Старайся давать осознаное название коммитам:
[pdate controllers]
[update manager v 1.04]
Ничего не понятно что было реально сделано, нужно убдет залезать в каждый коммит и смотреть. - это на будущее

2024-07-09 20:11 UTC, YazykovMikhail requested changes

2024-07-09 20:11 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/manager/Manager.java
> +        } catch (ValidationException e) {
не нужно обрабатывать это искоючение, ты же его сам создал и потом повторно обрабатываешь, сразу тогда возвращй null, но нет, 
Просто выбрасвай исключение и все, исключения - это тоже способ общение, способ сообщеить об ошибке, что бы тот кто вызвал знал о ней, а если вернется null ничего не помнтяно. Поправь везде

2024-07-09 20:11 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
@Slf4j- хороший, простой споосб для логирования 

Стандартный шаблон для логов
createMethod(Request request) {
log.info("пришел Post запрос /films с телом: {}", request)
Response response = //логика метода, если есть бизнес процессы для логирвоания логируем их
log.info("Отправлен ответ Post /films с телом: {}", response)
}
что бы было видно что пришло, что ушло и если были какие то изменения в процессы выполнянения тоже были видны, потому что ты пойдешь в логи когда у тебя что то сломалось, просто по сообщения "Фильм добалвен" ничего не понятно.

2024-07-09 20:11 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/manager/Manager.java
> +        if (users.isEmpty()) return null;
Возвращть null не стоит почти никогда. 
Просто возвращай  return new ArrayList<>(users.values());, если там нчиег онет вернется пустой список и будет понятно что нчиего нет

2024-07-09 20:11 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/manager/Manager.java
> +            } else return null;
{} - обязательны всегда
Если обьект не найдет для обновления - это исключение, нужно сообщеить о проблеме

2024-07-09 20:11 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/manager/Manager.java
> +        if (users.isEmpty()) return null;
Поправь везде

2024-07-09 20:11 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/manager/Manager.java
> +    protected int counterIdUser = -1;
ДУмаю стоит начинать с 0, иначем первым идетификатором будет 0, не думаю что такие идентификаторы существуют ;)

2024-07-09 20:11 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (manager.createUser(user) == null) {
Ты вызваешь метод который выполняет бизнес логику, что бы проверить условие, а потом его же вызываешь еще раз, но он только что был вызван. Получается дважды создание User. 
Эта проверка тут не нужна

2024-07-09 20:11 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (manager.createUser(user) == null) {
Касается и обнволения и User/Film методов

2024-07-09 20:11 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (manager.getUsers() == null) {
Тут тоже так лучше не делать, делаешь поиск по все БД, что бы проверить что не вернется null, а потом еще раз выполянешь тот жесамый запрос. Хоть после рефакторинг ты жто попарвитшь, но на будущее так делать ен стоит, альтернатива этого:
List<User> users = manager.getUsers();
if (users == null) {
// делаешь что нужно
}
return users

2024-07-09 20:11 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (manager.getUsers() == null) {
Но после рафторинга null тут быть не может, так что прост овозрващай значение

2024-07-10 15:13 UTC, 1EVILGUN1 commented
Оставил два условия null в putmapping потому что в postman без них выдает ошибки пытался пробросить в метода исключение но не получалось

2024-07-10 18:26 UTC, YazykovMikhail approved these changes

2024-07-10 18:26 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return createFilm(film);
ради такого выносить в метод не нужно, лучше все логику оставлять прям тут

2024-07-10 18:26 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +
Приватные методы обьявляются ниже публичных, сначала все смотреть контракты, потом уже детали реализации

2024-07-10 18:49 UTC, merged